# render.yaml（無料お試し向け：SQLite / Diskなし）
services:
  - type: web
    name: delivery-navigator
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
