# Generated by Django 5.2.7 on 2025-10-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deliveryrecord_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
