# Generated by Django 5.2.7 on 2025-10-04 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliveryrecord_end_time_deliveryrecord_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAiConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_aggregated', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['user', 'date'], name='core_delive_user_id_113464_idx'),
        ),
        migrations.AddField(
            model_name='useraiconsent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_consent', to=settings.AUTH_USER_MODEL),
        ),
    ]
