# Generated by Django 5.2.7 on 2025-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useraiconsent_deliveryrecord_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraiconsent',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='deliveryrecord',
            name='core_delive_user_id_113464_idx',
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='area_slug',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserAiConsent',
        ),
    ]
